Algoritmo "area do quadrado"
// Disciplina   : PA
// Professor   : Edilma
// Descrição   : Descobrir a area do quadrado
// Autor(a)    : Wesley Mendes de Sousa
// Data atual  : 09/03/2023
Var
// Seção de Declarações das variáveis 

area, lado : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite o lado do quadrado")
leia(lado)

area <- lado * lado
escreval ("a area do quadrado é: ", area)
Fimalgoritmo