Algoritmo "conversão celsius para fahreinheit"
// Disciplina   : PA
// Professor   : Edilma
// Descrição   : converter celsius para fahreinheit
// Autor(a)    : Wesley Mendes de Sousa
// Data atual  : 09/03/2023
Var
c, f : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite os graus celsius:")
leia(c)

f <- ((9*C+160)/5)

escreval("Você tem ",f," graus")
Fimalgoritmo