Algoritmo "salario"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : Wesley
// Data atual  : 25/05/2023



Var
salario, gasto :real



Inicio



//ENTRADA
escreval ("Começou")
escreval ("Digite seu salario: ")
leia (salario)
escreval ("Digite seus gastos: ")
leia (gasto)



//PROCESSO



se (gasto > salario) entao
escreval ("Saldo negativo")
senao
escreval ("Saldo positivo")
fimse

escreval ("Acabou")
Fimalgoritmo