Algoritmo "semnome"
// Disciplina   : PA
// Professor   : Edilma Bindá
// Autor(a)    : Wesley
// Data atual  : 25/05/2023



Var
numero :real



Inicio



//ENTRADA
escreval ("Começou")
escreval ("Digite um número: ")
leia (numero)



//PROCESSO



se (numero > 10) entao
escreval ("Esse número é maior que 10")
senao
escreval ("Esse número não é maior que 10")
fimse

escreval ("Acabou")
Fimalgoritmo